#ifndef FANNWASM_H_GENERATED_
#define FANNWASM_H_GENERATED_

#define WASM_CURR_MODULE_PREFIX 
/* Automically generated by wasm2c */
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

#include "wasm-rt.h"

#ifndef WASM_RT_MODULE_PREFIX
#define WASM_RT_MODULE_PREFIX
#endif

#define WASM_RT_PASTE_(x, y) x ## y
#define WASM_RT_PASTE(x, y) WASM_RT_PASTE_(x, y)
#define WASM_RT_ADD_PREFIX(x) WASM_RT_PASTE(WASM_RT_MODULE_PREFIX, x)

#define WASM_CURR_ADD_PREFIX(x) WASM_RT_PASTE(WASM_CURR_MODULE_PREFIX, x)

/* TODO(binji): only use stdint.h types in header */
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;

#ifndef WASM_DONT_EXPORT_FUNCS
# if defined(_WIN32)
#   define FUNC_EXPORT __declspec(dllexport)
# else
#   define FUNC_EXPORT
# endif
#else
# define FUNC_EXPORT
#endif

FUNC_EXPORT wasm2c_sandbox_funcs_t WASM_CURR_ADD_PREFIX(get_wasm2c_sandbox_info)();

struct wasm2c_sandbox_t;
typedef struct wasm2c_sandbox_t wasm2c_sandbox_t;

/* import: 'wasi_snapshot_preview1' 'proc_exit' */
extern void Z_wasi_snapshot_preview1Z_proc_exitZ_vi(void*, u32);
/* import: 'wasi_snapshot_preview1' 'clock_time_get' */
extern u32 Z_wasi_snapshot_preview1Z_clock_time_getZ_iiji(void*, u32, u64, u32);
/* import: 'wasi_snapshot_preview1' 'args_sizes_get' */
extern u32 Z_wasi_snapshot_preview1Z_args_sizes_getZ_iii(void*, u32, u32);
/* import: 'wasi_snapshot_preview1' 'args_get' */
extern u32 Z_wasi_snapshot_preview1Z_args_getZ_iii(void*, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_seek' */
extern u32 Z_wasi_snapshot_preview1Z_fd_seekZ_iijii(void*, u32, u64, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_write' */
extern u32 Z_wasi_snapshot_preview1Z_fd_writeZ_iiiii(void*, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_close' */
extern u32 Z_wasi_snapshot_preview1Z_fd_closeZ_ii(void*, u32);
/* import: 'wasi_snapshot_preview1' 'fd_fdstat_get' */
extern u32 Z_wasi_snapshot_preview1Z_fd_fdstat_getZ_iii(void*, u32, u32);
/* import: 'wasi_snapshot_preview1' 'path_filestat_get' */
extern u32 Z_wasi_snapshot_preview1Z_path_filestat_getZ_iiiiii(void*, u32, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_prestat_get' */
extern u32 Z_wasi_snapshot_preview1Z_fd_prestat_getZ_iii(void*, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_prestat_dir_name' */
extern u32 Z_wasi_snapshot_preview1Z_fd_prestat_dir_nameZ_iiii(void*, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'path_open' */
extern u32 Z_wasi_snapshot_preview1Z_path_openZ_iiiiiijjii(void*, u32, u32, u32, u32, u32, u64, u64, u32, u32);
/* import: 'wasi_snapshot_preview1' 'path_readlink' */
extern u32 Z_wasi_snapshot_preview1Z_path_readlinkZ_iiiiiii(void*, u32, u32, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'path_filestat_set_times' */
extern u32 Z_wasi_snapshot_preview1Z_path_filestat_set_timesZ_iiiiijji(void*, u32, u32, u32, u32, u64, u64, u32);
/* import: 'wasi_snapshot_preview1' 'path_unlink_file' */
extern u32 Z_wasi_snapshot_preview1Z_path_unlink_fileZ_iiii(void*, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'path_remove_directory' */
extern u32 Z_wasi_snapshot_preview1Z_path_remove_directoryZ_iiii(void*, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'path_create_directory' */
extern u32 Z_wasi_snapshot_preview1Z_path_create_directoryZ_iiii(void*, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_readdir' */
extern u32 Z_wasi_snapshot_preview1Z_fd_readdirZ_iiiiji(void*, u32, u32, u32, u64, u32);
/* import: 'wasi_snapshot_preview1' 'path_symlink' */
extern u32 Z_wasi_snapshot_preview1Z_path_symlinkZ_iiiiii(void*, u32, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'path_link' */
extern u32 Z_wasi_snapshot_preview1Z_path_linkZ_iiiiiiii(void*, u32, u32, u32, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'path_rename' */
extern u32 Z_wasi_snapshot_preview1Z_path_renameZ_iiiiiii(void*, u32, u32, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_fdstat_set_flags' */
extern u32 Z_wasi_snapshot_preview1Z_fd_fdstat_set_flagsZ_iii(void*, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_read' */
extern u32 Z_wasi_snapshot_preview1Z_fd_readZ_iiiii(void*, u32, u32, u32, u32);

FUNC_EXPORT void w2c__start(wasm2c_sandbox_t* const);
FUNC_EXPORT u32 w2c_fann_create_standard(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_fann_create_standard_array(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_fann_create_sparse_array(wasm2c_sandbox_t* const, f32, u32, u32);
FUNC_EXPORT void w2c_fann_seed_rand(wasm2c_sandbox_t* const);
FUNC_EXPORT u32 w2c_fann_allocate_structure(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_allocate_neurons(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_destroy(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_allocate_connections(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_fann_create_sparse(wasm2c_sandbox_t* const, f32, u32, u32);
FUNC_EXPORT u32 w2c_fann_create_shortcut(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_fann_create_shortcut_array(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_fann_run(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_fann_randomize_weights(wasm2c_sandbox_t* const, u32, f32, f32);
FUNC_EXPORT u32 w2c_fann_copy(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_fann_allocate_scale(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_print_connections(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_fann_get_total_neurons(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_fann_get_num_output(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_init_weights(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_fann_print_parameters(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_fann_get_num_input(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_fann_get_total_connections(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_fann_get_network_type(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT f32 w2c_fann_get_connection_rate(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_fann_get_num_layers(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_get_layer_array(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_fann_get_bias_array(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_fann_get_connection_array(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_fann_set_weight_array(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT void w2c_fann_set_weight(wasm2c_sandbox_t* const, u32, u32, u32, f32);
FUNC_EXPORT void w2c_fann_get_weights(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_fann_set_weights(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_fann_get_user_data(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_set_user_data(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_fann_disable_seed_rand(wasm2c_sandbox_t* const);
FUNC_EXPORT void w2c_fann_enable_seed_rand(wasm2c_sandbox_t* const);
FUNC_EXPORT u32 w2c_fann_create_from_file(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_fann_create_from_fd(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_fann_create_from_fd_1_1(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_fann_save(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_fann_save_internal(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_fann_save_internal_fd(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_fann_save_to_fixed(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT f32 w2c_fann_activation_derived(wasm2c_sandbox_t* const, u32, f32, f32, f32);
FUNC_EXPORT f32 w2c_fann_activation(wasm2c_sandbox_t* const, u32, u32, f32, f32);
FUNC_EXPORT void w2c_fann_train(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT void w2c_fann_compute_MSE(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_fann_backpropagate_MSE(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_update_weights(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT f32 w2c_fann_update_MSE(wasm2c_sandbox_t* const, u32, u32, f32);
FUNC_EXPORT u32 w2c_fann_test(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT f32 w2c_fann_get_MSE(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_fann_get_bit_fail(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_reset_MSE(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_update_slopes_batch(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT void w2c_fann_clear_train_arrays(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_update_weights_batch(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT void w2c_fann_update_weights_quickprop(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT void w2c_fann_update_weights_irpropm(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT void w2c_fann_update_weights_sarprop(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_fann_get_training_algorithm(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_set_training_algorithm(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT f32 w2c_fann_get_learning_rate(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_set_learning_rate(wasm2c_sandbox_t* const, u32, f32);
FUNC_EXPORT void w2c_fann_set_activation_function_hidden(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_fann_get_layer(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_fann_get_neuron_layer(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_fann_get_neuron(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_fann_get_activation_function(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT void w2c_fann_set_activation_function(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT void w2c_fann_set_activation_function_layer(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT void w2c_fann_set_activation_function_output(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_fann_set_activation_steepness_hidden(wasm2c_sandbox_t* const, u32, f32);
FUNC_EXPORT f32 w2c_fann_get_activation_steepness(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT void w2c_fann_set_activation_steepness(wasm2c_sandbox_t* const, u32, f32, u32, u32);
FUNC_EXPORT void w2c_fann_set_activation_steepness_layer(wasm2c_sandbox_t* const, u32, f32, u32);
FUNC_EXPORT void w2c_fann_set_activation_steepness_output(wasm2c_sandbox_t* const, u32, f32);
FUNC_EXPORT u32 w2c_fann_get_train_error_function(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_set_train_error_function(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_fann_get_callback(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_set_callback(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT f32 w2c_fann_get_quickprop_decay(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_set_quickprop_decay(wasm2c_sandbox_t* const, u32, f32);
FUNC_EXPORT f32 w2c_fann_get_quickprop_mu(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_set_quickprop_mu(wasm2c_sandbox_t* const, u32, f32);
FUNC_EXPORT f32 w2c_fann_get_rprop_increase_factor(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_set_rprop_increase_factor(wasm2c_sandbox_t* const, u32, f32);
FUNC_EXPORT f32 w2c_fann_get_rprop_decrease_factor(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_set_rprop_decrease_factor(wasm2c_sandbox_t* const, u32, f32);
FUNC_EXPORT f32 w2c_fann_get_rprop_delta_min(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_set_rprop_delta_min(wasm2c_sandbox_t* const, u32, f32);
FUNC_EXPORT f32 w2c_fann_get_rprop_delta_max(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_set_rprop_delta_max(wasm2c_sandbox_t* const, u32, f32);
FUNC_EXPORT f32 w2c_fann_get_rprop_delta_zero(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_set_rprop_delta_zero(wasm2c_sandbox_t* const, u32, f32);
FUNC_EXPORT f32 w2c_fann_get_sarprop_weight_decay_shift(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_set_sarprop_weight_decay_shift(wasm2c_sandbox_t* const, u32, f32);
FUNC_EXPORT f32 w2c_fann_get_sarprop_step_error_threshold_factor(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_set_sarprop_step_error_threshold_factor(wasm2c_sandbox_t* const, u32, f32);
FUNC_EXPORT f32 w2c_fann_get_sarprop_step_error_shift(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_set_sarprop_step_error_shift(wasm2c_sandbox_t* const, u32, f32);
FUNC_EXPORT f32 w2c_fann_get_sarprop_temperature(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_set_sarprop_temperature(wasm2c_sandbox_t* const, u32, f32);
FUNC_EXPORT u32 w2c_fann_get_train_stop_function(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_set_train_stop_function(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT f32 w2c_fann_get_bit_fail_limit(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_set_bit_fail_limit(wasm2c_sandbox_t* const, u32, f32);
FUNC_EXPORT f32 w2c_fann_get_learning_momentum(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_set_learning_momentum(wasm2c_sandbox_t* const, u32, f32);
FUNC_EXPORT u32 w2c_fann_read_train_from_file(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_fann_read_train_from_fd(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_fann_create_train(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT void w2c_fann_destroy_train(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_fann_save_train(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_fann_save_train_internal(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_fann_save_train_internal_fd(wasm2c_sandbox_t* const, u32, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_fann_save_train_to_fixed(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT f32 w2c_fann_test_data(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_fann_check_input_output_sizes(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT f32 w2c_fann_train_epoch_quickprop(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT f32 w2c_fann_train_epoch_irpropm(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT f32 w2c_fann_train_epoch_sarprop(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT f32 w2c_fann_train_epoch_batch(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT f32 w2c_fann_train_epoch_incremental(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT f32 w2c_fann_train_epoch(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_fann_train_on_data(wasm2c_sandbox_t* const, u32, u32, u32, u32, f32);
FUNC_EXPORT u32 w2c_fann_desired_error_reached(wasm2c_sandbox_t* const, u32, f32);
FUNC_EXPORT void w2c_fann_train_on_file(wasm2c_sandbox_t* const, u32, u32, u32, u32, f32);
FUNC_EXPORT void w2c_fann_shuffle_train_data(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_get_min_max_data(wasm2c_sandbox_t* const, u32, u32, u32, u32, u32);
FUNC_EXPORT f32 w2c_fann_get_min_train_input(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT f32 w2c_fann_get_max_train_input(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT f32 w2c_fann_get_min_train_output(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT f32 w2c_fann_get_max_train_output(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_scale_data(wasm2c_sandbox_t* const, u32, u32, u32, f32, f32);
FUNC_EXPORT void w2c_fann_scale_data_to_range(wasm2c_sandbox_t* const, u32, u32, u32, f32, f32, f32, f32);
FUNC_EXPORT void w2c_fann_scale_input_train_data(wasm2c_sandbox_t* const, u32, f32, f32);
FUNC_EXPORT void w2c_fann_scale_output_train_data(wasm2c_sandbox_t* const, u32, f32, f32);
FUNC_EXPORT void w2c_fann_scale_train_data(wasm2c_sandbox_t* const, u32, f32, f32);
FUNC_EXPORT u32 w2c_fann_merge_train_data(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_fann_duplicate_train_data(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_fann_subset_train_data(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_fann_length_train_data(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_fann_num_input_train_data(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_fann_num_output_train_data(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_fann_create_train_pointer_array(wasm2c_sandbox_t* const, u32, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_fann_create_train_array(wasm2c_sandbox_t* const, u32, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_fann_create_train_from_callback(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_fann_get_train_input(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_fann_get_train_output(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_fann_scale_input(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_fann_scale_output(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_fann_descale_input(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_fann_descale_output(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_fann_scale_train(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_fann_descale_train(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_fann_set_input_scaling_params(wasm2c_sandbox_t* const, u32, u32, f32, f32);
FUNC_EXPORT u32 w2c_fann_set_output_scaling_params(wasm2c_sandbox_t* const, u32, u32, f32, f32);
FUNC_EXPORT u32 w2c_fann_set_scaling_params(wasm2c_sandbox_t* const, u32, u32, f32, f32, f32, f32);
FUNC_EXPORT u32 w2c_fann_clear_scaling_params(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_reset_errno(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_reset_errstr(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_fann_get_errno(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_fann_get_errstr(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_set_error_log(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_fann_print_error(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_error(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT void w2c_fann_init_error_data(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_print_connections_raw(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_cascadetrain_on_data(wasm2c_sandbox_t* const, u32, u32, u32, u32, f32);
FUNC_EXPORT u32 w2c_fann_train_outputs(wasm2c_sandbox_t* const, u32, u32, f32);
FUNC_EXPORT u32 w2c_fann_initialize_candidates(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_fann_train_candidates(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_fann_install_candidate(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_set_shortcut_connections(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT f32 w2c_fann_train_outputs_epoch(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_fann_get_cascade_num_candidates(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_fann_reallocate_neurons(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_fann_reallocate_connections(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_initialize_candidate_weights(wasm2c_sandbox_t* const, u32, u32, u32, f32);
FUNC_EXPORT f32 w2c_fann_train_candidates_epoch(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_fann_add_layer(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_fann_add_candidate_neuron(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_fann_cascadetrain_on_file(wasm2c_sandbox_t* const, u32, u32, u32, u32, f32);
FUNC_EXPORT void w2c_fann_update_candidate_slopes(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_update_candidate_weights(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT f32 w2c_fann_get_cascade_output_change_fraction(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_set_cascade_output_change_fraction(wasm2c_sandbox_t* const, u32, f32);
FUNC_EXPORT u32 w2c_fann_get_cascade_output_stagnation_epochs(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_set_cascade_output_stagnation_epochs(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT f32 w2c_fann_get_cascade_candidate_change_fraction(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_set_cascade_candidate_change_fraction(wasm2c_sandbox_t* const, u32, f32);
FUNC_EXPORT u32 w2c_fann_get_cascade_candidate_stagnation_epochs(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_set_cascade_candidate_stagnation_epochs(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_fann_get_cascade_num_candidate_groups(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_set_cascade_num_candidate_groups(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT f32 w2c_fann_get_cascade_weight_multiplier(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_set_cascade_weight_multiplier(wasm2c_sandbox_t* const, u32, f32);
FUNC_EXPORT f32 w2c_fann_get_cascade_candidate_limit(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_set_cascade_candidate_limit(wasm2c_sandbox_t* const, u32, f32);
FUNC_EXPORT u32 w2c_fann_get_cascade_max_out_epochs(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_set_cascade_max_out_epochs(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_fann_get_cascade_max_cand_epochs(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_set_cascade_max_cand_epochs(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_fann_get_cascade_min_out_epochs(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_set_cascade_min_out_epochs(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_fann_get_cascade_min_cand_epochs(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_set_cascade_min_cand_epochs(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_fann_get_cascade_activation_functions_count(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_fann_get_cascade_activation_functions(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_set_cascade_activation_functions(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_fann_get_cascade_activation_steepnesses_count(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_fann_get_cascade_activation_steepnesses(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_fann_set_cascade_activation_steepnesses(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_malloc(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_dlmalloc(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_free(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_dlfree(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_calloc(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_realloc(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_dispose_chunk(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_posix_memalign(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_internal_memalign(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_aligned_alloc(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_malloc_usable_size(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_gettimeofday(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_abort(wasm2c_sandbox_t* const);
FUNC_EXPORT void w2c__Exit(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_sbrk(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_dummy(wasm2c_sandbox_t* const);
FUNC_EXPORT void w2c_exit(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_vsnprintf(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_sn_write(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_printf(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_fread(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_writev(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u64 w2c_scanexp(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_fwrite(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_fputs(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_vfscanf(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT void w2c_long_double_not_supported(wasm2c_sandbox_t* const);
FUNC_EXPORT u32 w2c_fscanf(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_fflush(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_dummy_1(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_fclose(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_strerror(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_vfprintf(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_printf_core(wasm2c_sandbox_t* const, u32, u32, u32, u32, u32);
FUNC_EXPORT void w2c_pop_arg(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT void w2c_long_double_not_supported_1(wasm2c_sandbox_t* const);
FUNC_EXPORT u32 w2c_fprintf(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_close(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_fstatat(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_getcwd(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_internal_register_preopened_fd(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_chdir(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_openat(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_faccessat(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_readlinkat(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_utimensat(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_mkdirat(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_fdopendir(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_opendirat(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_scandirat(wasm2c_sandbox_t* const, u32, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_sel_true(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_symlinkat(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_linkat(wasm2c_sandbox_t* const, u32, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_renameat(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_open(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_access(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_readlink(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_stat(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_lstat(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_utime(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_unlink(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_rmdir(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_remove(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_mkdir(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_opendir(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_scandir(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_symlink(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_link(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_rename(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_fcntl(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_readv(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_read(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_fopen(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_strdup(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_memmove(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_strcmp(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_strnlen(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_memcpy(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_strncmp(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_strcpy(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_memset(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_strlen(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_strchr(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_memchr(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_memcmp(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_dummy_2(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_qsort(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT void w2c_trinkle(wasm2c_sandbox_t* const, u32, u32, u32, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_wctomb(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_wcrtomb(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_mbrtowc(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_mbsinit(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_srand(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_rand(wasm2c_sandbox_t* const);
FUNC_EXPORT f64 w2c_log(wasm2c_sandbox_t* const, f64);
FUNC_EXPORT f64 w2c_pow(wasm2c_sandbox_t* const, f64, f64);
FUNC_EXPORT f64 w2c_sin(wasm2c_sandbox_t* const, f64);
FUNC_EXPORT f64 w2c_frexp(wasm2c_sandbox_t* const, f64, u32);
FUNC_EXPORT f32 w2c_cosf(wasm2c_sandbox_t* const, f32);
FUNC_EXPORT f32 w2c_sinf(wasm2c_sandbox_t* const, f32);
FUNC_EXPORT f64 w2c_cos(wasm2c_sandbox_t* const, f64);
FUNC_EXPORT f64 w2c_exp(wasm2c_sandbox_t* const, f64);
FUNC_EXPORT f64 w2c_scalbn(wasm2c_sandbox_t* const, f64, u32);
FUNC_EXPORT f64 w2c_fmod(wasm2c_sandbox_t* const, f64, f64);
FUNC_EXPORT f32 w2c_expf(wasm2c_sandbox_t* const, f32);

#ifdef __cplusplus
}
#endif

#endif  /* FANNWASM_H_GENERATED_ */
